### ISSUE TITLE
v0.0.11-rc2 command prompt does not finish command.

### ISSUE THREAD

**Issue by Br1ck5t3r** [gizmo-platform/gizmo#6]
Even after changing directories, When I try running the command 

`gizmo firmware configure`

This results in nothing appearing an merely asking for a new command. Is this on my side or is this a bug?

![2024-02-16](https://github.com/BESTRobotics/gizmo/assets/159820151/0f405a7e-3f2e-4c72-8148-7522c2a860ee)

**Comment by Br1ck5t3r** [comment]
Further note, if I was to use the config file form v0.0.11-rc1, would it fail?

**Comment by the-maldridge** [comment]
That is a really weird bug.  Here's what I think is happening:

The command prompt is rooted in [1980's computer arcana](https://xkcd.com/1671/).  This means that it handles modern concepts somewhat differently than we would expect it to.  The firmware configure command makes use of a library to print pretty terminal prompts and allow you to click on things rather than having to do everything in a line oriented context.  I think that what's happening is that the prompts are all getting written into `NUL` due to a windows stream processing choice that makes `cmd.exe` backwards compatible.

I know for sure this works in powershell, and I'm trying to replicate your screenshot here to see if I can work out what's going on.

As for the config file, we haven't changed any of the formats in the config files in a while, and in general we try to make sure we can continue to read old config files in newer versions, though this isn't always guaranteed.  What is guaranteed is that we'll print an error if parsing the config file fails, so if you try it and don't get an error, we were able to read the file successfully.

**Comment by the-maldridge** [comment]
Closing this as obsolete, please re-verify on a current version.
